import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import indexStyles from "../styles/Index.module.css";
import szrenica from "../public/images/szrenica1.jpg";
import navStyles from "../styles/navbar.module.css";
import kotly from "../public/images/kotly.jpg";
import pies from "../public/images/pies.jpg";

export default function Home() {
  return (
    <div className={indexStyles.container}>
      <Head>
        <title>Art Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={indexStyles.sectionsWrapper}>
        <section>
          <header className={indexStyles.header}>
            <h1>Art Landing Page</h1>
          </header>
          <a
            href="#main-menu"
            className={navStyles.menuToggle}
            id="main-menu-toggle"
          >
            <span>
              <Image
                src="/bars-solid.svg"
                height={30}
                width={30}
                className={navStyles.barsIcon}
              />
            </span>
          </a>
          <nav className={navStyles.navigationWrapper} id="main-menu">
            <a href="#main-menu-toggle" className={navStyles.menuClose}>
              X
            </a>
            <ul>
              <li className={navStyles.navButton}>Start</li>
              <li className={navStyles.navButton}>Galeria</li>
              <li className={navStyles.navButton}>Kontakt</li>
              <li className={navStyles.navButton}>O mnie</li>
            </ul>
          </nav>
          <div className={indexStyles.sectionOneImageContainer}>
            <div>
              <Image src={szrenica} alt="Szrenica" layout="fill"></Image>
            </div>
          </div>
        </section>
        <section id="section-two"></section>
        <section id="section-three"></section>
      </div>
    </div>
  );
}
