import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import indexStyles from "../styles/Index.module.css";
import indexS2Styles from "../styles/Index_section2.module.css";
import indexS3Styles from "../styles/index_section3.module.css";
import szrenica from "../public/images/szrenica1.jpg";
import navStyles from "../styles/navbar.module.css";
import kotly from "../public/images/kotly.jpg";
import pies from "../public/images/pies.jpg";
import { useEffect, useState } from "react";

export default function Home() {
  return (
    <div className={indexStyles.container}>
      <Head>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Alumni+Sans+Pinstripe&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Alumni+Sans+Pinstripe:ital@1&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Aboreto&family=Alumni+Sans+Pinstripe&family=Bad+Script&display=swap"
          rel="stylesheet"
        ></link> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Aboreto&family=Alumni+Sans+Pinstripe&family=Bad+Script&family=Bodoni+Moda:opsz@6..96&display=swap"
          rel="stylesheet"
        ></link>
        <title>Art Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={indexStyles.sectionsWrapper}>
        <section>
          <header className={indexStyles.header}>
            <h1>Monika Krakowska Art</h1>
          </header>
          <a
            href="#main-menu"
            className={navStyles.menuToggle}
            id="main-menu-toggle"
          >
            <span>
              <Image
                src="/bars-solid.svg"
                height={30}
                width={30}
                className={navStyles.barsIcon}
              />
            </span>
          </a>
          <nav className={navStyles.navigationWrapper} id="main-menu">
            <a href="#" className={navStyles.menuClose}>
              <span className={navStyles.xmarkIcon}>
                <Image src="/xmark-solid.svg" height={30} width={30} />
              </span>
            </a>
            <ul>
              <li className={navStyles.navButton}>Start</li>
              <li className={navStyles.navButton}>Galeria</li>
              <li className={navStyles.navButton}>Kontakt</li>
              <li className={navStyles.navButton}>O mnie</li>
            </ul>
          </nav>
          <div className={indexStyles.sectionOneImageContainer}>
            <div>
              <Image src={szrenica} alt="Szrenica" layout="fill"></Image>
              <div className={indexStyles.testclass}>
                Śnieżka
                <p>Olej na płótnie</p>
              </div>
            </div>
          </div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
            placerat lectus at mauris elementum malesuada. Nunc fringilla purus
            nec tortor malesuada, quis feugiat diam porta. Mauris vulputate
            magna ac ligula aliquet, at fermentum ex mattis. Donec a efficitur
            libero. Duis est ligula, commodo a sem sit amet, pharetra pharetra
            ligula.
          </p>
        </section>
        <section id="section-two">
          <p>
            Śnieżne kotły latem. Aenean sed pharetra lacus, vitae pellentesque
            est. Integer augue tellus, pharetra non ultrices at, hendrerit eu
            leo.{" "}
          </p>
          <div className={indexStyles.sectionOneImageContainer}>
            <div>
              <Image src={kotly} alt="Ktoły" layout="fill"></Image>
            </div>
            <div className={indexS2Styles.backgroundText}>Pejzaże</div>
          </div>
          <div className={indexStyles.pageBreak}></div>
        </section>
        <section id="section-three">
          <div className={indexStyles.pageBreak}>
            <div></div>
          </div>
          <div className={indexS3Styles.sectionThreeImageContainer}>
            <div>
              <Image src={pies} alt="Ktoły" layout="fill"></Image>
            </div>
            <div className={indexS3Styles.backgroundText}>
              PIĘKNO <br></br> NATURY <br></br> UWIECZNIONE
            </div>
          </div>
          <div className={indexStyles.pageBreak}></div>
        </section>
        <footer>Design and execution - Bartlomiej Witek 2022</footer>
      </div>
    </div>
  );
}
